---

- name: Copy CA
  copy:
    src: ca{{ item }}.pem
    dest: /root/ca{{ item }}.pem
  become: Yes
  with_items:
    - "-key"
    - ""

- name: Copy kubernetes certificate
  copy:
    src: kubernetes{{ item }}.pem
    dest: /root/kubernetes{{ item }}.pem
  become: Yes
  with_items:
    - "-key"
    - ""

- name: Copy service-account certificate
  copy:
    src: service-account{{ item }}.pem
    dest: /root/service-account{{ item }}.pem
  become: Yes
  with_items:
    - "-key"
    - ""

- name: Copy kubeconfigs
  copy:
    src: "{{ item }}.kubeconfig"
    dest: /root/{{ item }}.kubeconfig
  become: Yes
  with_items:
    - admin
    - kube-controller-manager
    - kube-scheduler

- name: Generate encryption key
  command: bash -c "head -c 32 /dev/urandom | base64"
  register: encryption_key

- name: Copy encryption config
  template:
    src: encryption-config.yml
    dest: /root/encryption-config.yml
    mode: 0644
  become: Yes


